---
title: "Construction of the global neural crest gene regulatory network *in vivo*"
author: ""
output: html_document
---

### Manuscript and contact information
Construction of the global neural crest gene regulatory network _in vivo_.

Ruth M Williams<sup>1</sup>, Ivan Candido-Ferreira<sup>1</sup>, Emmanouela Repapi<sup>2</sup>, Daria Gavriouchkina<sup>1,4</sup>, Upeka Senanayake<sup>1</sup>, Jelena Telenius<sup>3</sup>, Stephen Taylor<sup>2</sup>, Jim Hughes<sup>3</sup> and Tatjana Sauka-Spengler<sup>1,ยง</sup>.

 ยง Corresponding author: 
 Tatjana Sauka-Spengler (tatjana.sauka-spengler@imm.ox.ac.uk)

### Affiliations 

1. University of Oxford,
MRC Weatherall Institute of Molecular Medicine,
Radcliffe Department of Medicine,
Oxford, OX3 9DS, UK

2. University of Oxford,
MRC WIMM Centre for Computational Biology,
Weatherall Institute of Molecular Medicine,
Oxford, OX3 9DS, UK

3. University of Oxford,
MRC Molecular Haematology Unit,
Weatherall Institute of Molecular Medicine,
Oxford, OX3 9DS, UK

4. Present address:
Okinawa Institute of Science and Technology,
Molecular Genetics Unit,
Onna, 904-0495, Japan



Ruth M Williams, Ivan Candido-Ferreira, Daria Gavriouchkina, Upeka Senanayake, Tatjana Sauka-Spengler: [Sauka-Spengler lab](http://www.tsslab.co.uk) based at [MRC Weatherall Institute of Molecular Medicine](www.imm.ox.ac.uk) and [Radcliffe Department of Medicine, University of Oxford] (http://www.rdm.ox.ac.uk)

Emmanouela Repapi, Stephen Taylor: [Taylor group](https://www.imm.ox.ac.uk/research/units-and-centres/mrc-wimm-centre-for-computational-biology/groups/taylor-group-visualisation-analysis-and-integration) based at [MRC Weatherall Institute of Molecular Medicine](http://www.imm.ox.ac.uk)

Jelena Telenius, Jim Hughes: [Hughes lab](https://www.imm.ox.ac.uk/research/units-and-centres/mrc-wimm-centre-for-computational-biology/groups/hughes-group) based at [MRC Weatherall Institute of Molecular Medicine](http://www.imm.ox.ac.uk) and [Radcliffe Department of Medicine, University of Oxford] (http://www.rdm.ox.ac.uk)

### Keywords

Neural crest, gene regulatory network, chick, enhancers, ATAC, super-enhancers, Capture-C, transcription factors

### Research Organism

*Gallus gallus*




